### ISSUE TITLE
deeper-chain got crashed with error messages

### ISSUE THREAD

**Issue by donileongdeepernetwork** [deeper-chain/deeper-chain#80]
```bash
Aug 31 17:23:13 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: 2021-08-31 17:23:13  💤 Idle (9 peers), best: #57062 (0x3edc…f108), finalized #57060 (0xbf09…0611), ⬇ 10.9kiB/s ⬆ 10.2kiB/s
Aug 31 17:23:15 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: 2021-08-31 17:23:15  ✨ Imported #57063 (0x8c47…0903)
Aug 31 17:23:18 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: 2021-08-31 17:23:18  💤 Idle (9 peers), best: #57063 (0x8c47…0903), finalized #57061 (0x797f…5f0d), ⬇ 13.8kiB/s ⬆ 11.6kiB/s
Aug 31 17:23:20 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: 2021-08-31 17:23:20  🙌 Starting consensus session on top of parent 0x8c47f12cd58c88e0a2964c68ff378c88905f0c76def1f9f6e89ed976aa620903
Aug 31 17:23:20 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: 2021-08-31 17:23:20  🎁 Prepared block for proposing at 57064 [hash: 0xb3a58cb878f4713ec3712a9ae329e1e0cc81b24c5e59358ec5e9b807e0951bf0; parent_hash: 0x8c47…0903; extrinsics (1): [0xf399…ac7a]]
Aug 31 17:23:20 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: 2021-08-31 17:23:20  🔖 Pre-sealed block for proposal at 57064. Hash now 0xc06b2aeb6ffd1e6d5c78a95a28634c9226098583348fc1f99490f4c4b59066e4, previously 0xb3a58cb878f4713ec3712a9ae329e1e0cc81b24c5e59358ec5e9b807e0951bf0.
Aug 31 17:23:20 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: 2021-08-31 17:23:20  ✨ Imported #57064 (0xc06b…66e4)
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: ====================
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: Version: 2.0.0-28811e7-x86_64-linux-gnu
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    0: sp_panic_handler::set::{{closure}}
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    1: std::panicking::rust_panic_with_hook
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:              at /rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/panicking.rs:595:17
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    2: std::panicking::begin_panic::{{closure}}
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    4: std::panicking::begin_panic
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    5: <libp2p_swarm::toggle::ToggleProtoHandler<TInner> as libp2p_swarm::protocols_handler::ProtocolsHandler>::inject_listen_upgrade_error
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    6: <libp2p_swarm::protocols_handler::select::ProtocolsHandlerSelect<TProto1,TProto2> as libp2p_swarm::protocols_handler::ProtocolsHandler>::inject_listen_upgrade_error
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    7: <libp2p_swarm::protocols_handler::node_handler::NodeHandlerWrapper<TProtoHandler> as libp2p_core::connection::handler::ConnectionHandler>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    8: libp2p_core::connection::Connection<TMuxer,THandler>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:    9: <libp2p_core::connection::manager::task::Task<F,M,H,I,O,E> as core::future::future::Future>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   10: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   11: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   13: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   14: <sc_service::task_manager::WithTelemetrySpan<T> as core::future::future::Future>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   15: tokio::runtime::task::core::Core<T,S>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   17: tokio::runtime::task::harness::Harness<T,S>::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   18: std::thread::local::LocalKey<T>::with
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   19: tokio::runtime::thread_pool::worker::Context::run_task
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   20: tokio::runtime::thread_pool::worker::Context::run
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   21: tokio::macros::scoped_tls::ScopedKey<T>::set
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   22: tokio::runtime::thread_pool::worker::run
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   24: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   25: tokio::runtime::task::raw::poll
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   26: tokio::runtime::blocking::pool::Inner::run
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   27: tokio::runtime::context::enter
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   28: std::sys_common::backtrace::__rust_begin_short_backtrace
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   29: core::ops::function::FnOnce::call_once{{vtable.shim}}
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:              at /rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/alloc/src/boxed.rs:1546:9
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:              at /rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/alloc/src/boxed.rs:1546:9
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:       std::sys::unix::thread::Thread::new::thread_start
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:              at /rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/sys/unix/thread.rs:71:17
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   31: start_thread
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:   32: clone
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: Thread 'tokio-runtime-worker' panicked at 'Unexpected Either::Right on enabled `inject_listen_upgrade_error`.', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.1/src/toggle.rs:288
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]: This is a bug. Please report it at:
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network deeper-chain[38377]:         https://github.com/paritytech/substrate/issues/new
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network systemd[1]: deeper-chain.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 17:23:22 ap-east-1-001-mainnet-chain.deeper.network systemd[1]: deeper-chain.service: Failed with result 'exit-code'.
Aug 31 17:23:27 ap-east-1-001-mainnet-chain.deeper.network systemd[1]: deeper-chain.service: Scheduled restart job, restart counter is at 1.
```

**Comment by lzw65** [comment]
# update libp2p-swarm from v0.27.1 to v0.27.2
cargo update -p libp2p-swarm
